id: create_logs
learningObjectives: 
- Transfer Data 
hints:
- Try to find all the total number of books
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Recently, we lost all the important system logs because we didn't have backup log. We're taking an initiative to implement a log backup system to prevent this from happening again."
        delay: 2000
      - text: "Set up a local Apache web server on your machine and we'll back up the logs by executing `create_logs.py`. What the name of the file stroring the logs"
        delay: 3500
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_match_regex
        params:
          text: "${userMessageText}"
          regex: access|access.log
          flags: i
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: Great! Let's continue.
              delay: 1300
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: Try again! I'm sure you'll figure this out.
              delay: 2500
githubActions:
  backend:
    capabilities:
    - puppeteer
    testFile: "profile.test.js"  
