id: create_folder
learningObjectives: 
- Learn about navigating files using the Linux terminal. Execute at least a single command to manipulate files and directory in Linux.
hints:
- A root directory is the top most directory in the hierarchy.
- You can find instructions on creating folders in Linux [here]
  (https://fumbani.hashnode.dev/creating-and-deleting-folders-in-linux)
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Hi ${user.firstName}. Recently, we lost all the important system logs because we didn't have backup log. We're taking an initiative to implement a log backup system to prevent this from happening again."
        delay: 2000
      - text: "One thing you need to understand about logs is being organized matters."
        delay: 2000
      - text: "Please create a new directory under the root directory called `backups`. This where we'll keep all our backups."
        delay: 2000
      - text: "Let me know when you're done by typing `Done`."
        delay: 3500
      person: 

trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
          - "Done"
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Great!!!" 
              delay: 2000
            - text: "You're good with the Linux terminal."
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Are you sure? This doesn't make sense..."
              delay: 2500