id: funneldrop_fixing_bug_pr
learningObjectives: 
- Fixing a bug 
hints:
- Try to inspect the problematic view and see where it is on the screen
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "We are almost there. We don't need you to be creating backups manually everytime. Please reate a new script under the scripts directory in the backend directory called `backup_daily.sh`"
        delay: 1500
      - text: "The script should take in a directory name and create an archive from the directory. Use tar and gzip, it's the standard around here."
        delay: 1500
      - text: "I have to head out for a bit, but just create a PR when you're done and I'll review it."

githubActions:
  backend:
    testFile: "profile.test.js"
    cmd: "bash ${testFile}"
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
          - actionId: bot_message
            params:
              person: keen
              messages:
              - text: "On it, I'll review the changes right away."
                delay: 1000
          - actionId: github_pr_comment
            params:
              person: keen
              message: "On it, I'll review the changes right away."
        github_pr_workflow_complete_success:
          do:
          - actionId: bot_message
            params:
              person: keen
              messages:
              - text: "Nailed it! Excellent job @${user.githubuser}! You can now merge the PR."
                delay: 2000
          - actionId: github_pr_approve
            params:
              person: keen
              message: "Nailed it! Excellent job @${user.githubuser}! You can now merge the PR."
        github_pr_workflow_complete_failure:
          do:
          - actionId: bot_message
            params:
              person: keen
              messages:
              - text: "Make sure your fix passes all the checks, then try again please."
                delay: 3000
          - actionId: github_pr_reject
            params:
              person: keen
              message: "Looks like this code change didn’t fix the problem. Can you take a second look?"
        github_pr_merged:
          do:
          - actionId: finish_step
